{% set name = "click-aliases" %}
{% set version = "1.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz"
  sha256: 6187abb0b59cb490e7d8baba3615c53f0ea5dc9c2b08435c2230fdc84a34c5dd

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - click
    - pip
    - python >=3
  run:
    - click
    - python >=3

test:
  imports:
    - click_aliases

about:
  home: "https://github.com/click-contrib/click-aliases"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Enable aliases for Click"

extra:
  recipe-maintainers:
    - tedil
