{% set name = "click-aliases" %}
{% set version = "1.0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz"
  sha256: 384313c5dc4c4bd64d9eadaff39ad91352747e8cdfd2f95d504d914c01eb4eda

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - click
    - pip
    - python >=3
  run:
    - click
    - python >=3

test:
  imports:
    - click_aliases

about:
  home: "https://github.com/click-contrib/click-aliases"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Enable aliases for Click"

extra:
  recipe-maintainers:
    - tedil
